stages:
- name: Build Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: api-demo
      registry: 127.0.0.1:34729
- name: Charts
  steps:
  - publishCatalogConfig:
      path: chart
      catalogTemplate: api-demo
      version: ${CICD_GIT_TAG}
      gitUrl: https://github.com/dahendel/helm-charts-testing.git
      gitBranch: master
      gitAuthor: dahendel
      gitEmail: dustinhendel@gmail.com
    envFrom:
    - sourceName: ns-g9wtr
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: ns-g9wtr
      sourceKey: PASSWORD
      targetKey: PASSWORD
timeout: 60
notification: {}
